spring.application.name=casino-core-api

spring.datasource.url=jdbc:postgresql://localhost:5432/casino_core
spring.datasource.username=postgres
spring.datasource.password=Josias123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true